koushik369mondal/WanderLust

package-lock.json
views/error.ejs

for issue raised no. #18 
Sir i added the 404 error page for the unknown url at branch "feature/404_page". In that change i mainly make changes in error.ejs file 
Please Look on to it sir.
I am waiting for your reply. 
---
This PR updates project licensing metadata and enhances the error page UI.
- package-lock.json: License field changed from 'ISC' to 'MIT'
- views/error.ejs: Complete redesign to a themed, user-friendly 404 error page with custom styles and navigation options

add: 404 error page for unknown url

---

package-lock.json
public/CSS/style.css
public/JS/script.js
views/includes/navbar.ejs

This pull request introduces a dark mode feature to the application, allowing users to toggle between light and dark themes. The implementation enhances the visual accessibility and reduces eye strain, especially in low-light environments.
Changes Made:
Added a dark mode toggle button in the UI.
Defined dark mode color variables and styles in CSS.
Implemented JavaScript/React logic to switch themes and persist user preference.
Ensured compatibility with existing components and responsiveness.
Tested across multiple browsers and screen sizes for consistent appearance.
---
- Refactored CSS for dynamic light/dark theme support using custom properties
- Added ThemeManager and SearchManager classes in JS for theme toggling and search handling
- Introduced a theme toggle button in the navbar
- …

Dark mode functionality 

---

controllers/users.js
models/user.js
routes/user.js
views/includes/navbar.ejs
views/users/profile.ejs

For issue Raised #13 
Sir in this Pull request i am ensuring the profile page fully responsive in both mobile and desktop view.
This Page is with both light and dark mode.
In this page sir i also worked with editing feature that's an extra one.
Screenshots:

added the profile page with editing enabled

---

public/CSS/style.css
views/listings/index.ejs

closes #44 
@koushik369mondal please check it.

enhanced footer design

---

public/CSS/style.css
views/listings/index.ejs

Reverts koushik369mondal/WanderLust#87

Revert "enhanced footer design"

---

.env.example
public/CSS/style.css
views/users/login.ejs
views/users/signup.ejs

signup and signin page interface enhanced 
issue #103 
---
- Standardized environment variable names in .env.example
- Enhanced and modernized authentication form styling in public/CSS/style.css
- Refactored login and signup views to use new CSS classes and improved structure for maintainability

Insufficient Padding in the Sign-Up Form Container

---

app.js
controllers/listings.js
init/index.js
models/listing.js
public/JS/map.js
routes/listing.js
views/listings/index.ejs
views/listings/show.ejs

Fixes #12 
---
This PR implements a listing like/unlike feature while temporarily disabling Mapbox functionality for development purposes.
- Added 'likes' array field to listing schema to track users who liked a listing
- Created likeListing and unlikeListing controller methods and corresponding routes
- Added UI components for like/unlike functionality with conditional rendering
- Improved error handling for missing data in listing views
- Commented out Mapbox-related code (geocoding, map display, token validation)
- Standardized code formatting and indentation across multiple files
- Updated hardcoded owner ID in initialization data

like-feature added

---

.github/workflows/issue-create-automate-message.yml
.github/workflows/pr-create-automate-message.yml

I have added the issue create automate message github actions bot. Please @koushik369mondal check and merge the PR and add the gssoc25 label along with the level of contribution, Let me know if require any changes.
fixes #108 
---
This PR adds automated GitHub workflows that post standardized thank-you messages on newly created issues and pull requests.
- Added workflow for issues that provides guidance on reviewing documentation and waiting for assignment
- Added workflow for PRs that acknowledges contributions and encourages addressing review comments
- Both workflows use the github-script action to post comments
- PR workflow includes explicit permissions configuration for issues and pull requests

Issue create automate message

---

app.js
views/about.ejs
views/users/profile.ejs

solved #90 
https://github.com/user-attachments/assets/4083059a-efb6-48c9-a4e2-3b05f8ae7b59
Hello @koushik369mondal Please add label in it ,Thank you!
---
This PR adds an About Us page and improves the user profile interface.
- Added '/about' route handler in app.js
- Created views/about.ejs with company information and custom styling
- Refactored views/users/profile.ejs with modern design elements, improved responsive behavior, and consolidated CSS
- Moved from inline styles to a consolidated style block in profile page
- Enhanced visual hierarchy and styling consistency across pages

Improved Profile Section UI

---

public/CSS/loading.css
public/JS/loading.js
views/layouts/boilerplate.ejs

issue #128 
loading spinner added for async operations

loading spinner added

---

public/CSS/style.css

**Description:**
This PR addresses the low contrast issue on the Login and Signup pages, making input placeholders (Username, Email, Password) and footer link text more readable against bright background images.
**Changes Made:**
- Darkened the placeholder text in all input fields.
- Updated the footer link text color to increase contrast.
- Added a semi-transparent overlay behind the form container to ensure text visibility on varying background brightness.
- Verified text contrast against WCAG accessibility guidelines.
**Screenshots (Before & After):**
**Steps to Verify:**
1. Navigate to the Signup page.
- Observe that input placeholders and footer links are now clearly visible.
2. Navigate to the Login page.
- Observe the same improvement in readability.
3. Test across different screen …

Fix: Improve text contrast on Login and Signup pages for better readability

---

public/CSS/style.css
views/privacy.ejs

solved #141 
📖 Description
This PR enhances the Privacy Policy page UI by adding a glassmorphism effect for a modern and visually appealing design.
✅ Changes Made
Added backdrop-filter: blur() and semi-transparent background.
Updated CSS classes to apply glassmorphism styling.
Ensured accessibility with proper text contrast.
https://github.com/user-attachments/assets/6288a9d9-77da-4c74-a963-91aeebc5b57b
🔍 Testing
Verified UI changes on desktop view.
Verified on mobile/tablet view.
Checked readability with different background images/colors.
Hello @koushik369mondal ,Add label in it Thank you!
---
This PR improves cross-browser compatibility and updates the privacy page styling.
- Added -webkit-backdrop-filter properties alongside existing backdrop-filter properties in multiple CSS …

Added Glassmorphism Effect on privacy page

---

public/CSS/style.css
views/about.ejs

solved #121 
📖 Description
This PR enhances the About page UI by adding a glassmorphism effect for a modern and visually appealing design.
Hello @koushik369mondal, Please add label in it Thank You!
---
This PR enhances UI consistency for the about page by standardizing container styling.
- Added '.about-container' to borderless container selectors in style.css
- Replaced generic 'container' class with specific 'about-container' class in about.ejs
- Removed redundant line-height CSS definition that conflicted with inline styling

Added Glassmorphism to about page

---

SPARKLE_IMPROVEMENTS.md
public/CSS/style.css
public/JS/script.js

- Closes N/A - Bug fix and performance enhancement
This PR fixes a critical bug where JavaScript code referenced CSS animations (`fadeOut` and `flicker`) that didn't exist, causing potential console errors. Additionally, it enhances the sparkle effect with performance optimizations and accessibility improvements to make the application more inclusive and performant.
- **🐛 Bug Fix**: Added missing `fadeOut` and `flicker` CSS keyframe animations that were referenced in JavaScript
- **⚡ Performance**: Added throttling (60fps), limited concurrent sparkles (max 15), and proper memory cleanup
- **♿ Accessibility**: Added support for `prefers-reduced-motion` preference and `aria-hidden` attributes
- **🎨 Visual Enhancement**: Expanded color palette (8 vibrant colors) and improved animation timing …

Fix/add missing sparkle animations [GSSoC 25]

---

controllers/listings.js
views/includes/navbar.ejs
views/listings/index.ejs

- Closes #161 
All the filters in the project are now functioning! 
Users can now filter listings based on categories and then clear the filters later to see all listings together again.
The homepage UI includes a filter bar with various category icons (e.g., Mountains, Camping), but these were previously static and non-functional. This PR activates these icons, turning them into a core navigation feature. This allows users to easily discover listings that match their interests, significantly improving the browsing experience and making the application more interactive and user-friendly.
1. Backend Enhancements:
--Controller Logic: The index controller in controllers/listings.js has been updated to parse URL query parameters (req.query.category).
--Dynamic Database Querying: The …

Feature: Implement Category Filtering on Main Listings Page

---

controllers/listings.js
controllers/users.js
models/user.js
routes/user.js
views/includes/navbar.ejs
views/users/liked.ejs

- Closes #166 
This PR activates the 'like' functionality by creating a dedicated "Liked Listings" page. This allows users to track and revisit their favorite places, making the like feature a meaningful tool for trip planning and significantly improving user engagement.
Database: Updated User and Listing schemas with a likes field.
Backend: Created a new route (GET /profile/likes) and controller function that uses .populate('likes') to serve a user's saved listings. Updated like/unlike logic for better consistency.
Frontend & UI: Created a new view file, views/users/liked.ejs, to display liked items. Converted the "Profile" link into a dropdown menu and added flash messages for user feedback.
Yes, tested by liking/unliking, verifying the flash message, navigating by the new profile …

Feature: A personalized section of liked listings achieved

---

public/JS/script.js
views/listings/edit.ejs
views/listings/new.ejs

The forms for creating a new listing (/listings/new) and editing an existing one (/listings/:id/edit) do not have any client-side validation. A user can submit the form with empty required fields like "Title", "Description", or "Price".
The submission is correctly rejected by the server-side validation (using Joi), but this requires a full page reload to show the error message. This isn't a great user experience.
So I provided immediate feedback to the user by adding basic HTML5 client-side validation. By simply adding the required attribute to the necessary and <textarea> elements, the browser will prevent the form from being submitted if those fields are left empty. 
---
This PR improves code quality and fixes bugs across the application without changing core functionality.
- Refactored …

Updated the necessary files.

---

views/listings/new.ejs

- Closes #176.
The old “Create Listing” form had poor text visibility on the dark background and lacked an image preview feature.
This update improves the user experience by making the form more aesthetic, accessible, and user-friendly.
Improved label and placeholder visibility on dark background
Styled inputs, selects, and submit button for consistency with the theme
Old Pages
Light Themed
Dark Themed
New pages 
Light Themed
Dark Themed
---
This PR modernizes the listing creation form with an enhanced UI and improved user experience.
- Implemented glass-morphism dark-themed UI with gradients, shadows, and hover effects
- Added client-side image preview functionality with JavaScript
- Enhanced form usability with better spacing, styling, and visual feedback
- Improved accessibility by …

FIXED: Improved create listing form

---

controllers/listings.js
init/data.js
models/listing.js
routes/listing.js
views/includes/navbar.ejs
views/listings/index.ejs

- Closes #178 
The website's header contains a prominent search bar, which is a key feature for user navigation. Currently, this search bar is a non-functional UI element. Users have no way to search for specific listings based on keywords, locations, or categories, which limits the platform's usability and makes it difficult to find specific content.
his PR introduces a full-stack search functionality.
Backend:
-A new route (GET /listings/search) was added to routes/listing.js to handle search requests.
-A new controller function (searchListings) was implemented to parse the URL query parameter (req.query.q).
-This controller performs a case-insensitive, multi-field database search using Mongoose's $or and $regex operators to find matches in the listing's title, category, location, and …

Implement search feature logic from scratch to make search bar functional

---

public/CSS/style.css

- **Issue #94**: Poor font visibility and contrast across the platform
- Text readability issues affecting user experience and accessibility
- Insufficient contrast ratios not meeting WCAG 2.1 AA standards
- Inconsistent typography hierarchy and font weights
- Mobile readability concerns with small font sizes
Comprehensive typography overhaul to improve visibility, accessibility, and user experience across all components and themes.
- ✅ Enhanced navigation links with `font-weight: 500` and `font-size: 1rem`
- ✅ Improved dark theme navigation with pure white text (`#ffffff`)
- ✅ Better visual hierarchy and consistency
- ✅ Strengthened form labels with `font-weight: 600` and `font-size: 1rem`
- ✅ Enhanced dark theme input fields with better background contrast (0.15 opacity)
- ✅ Improved …

fix: enhance font visibility and readability across the platform [GSSoC 2025]

---

app.js
controllers/listings.js
controllers/users.js
middleware.js
models/badgeDefinition.js
models/user.js
models/wishlist.js
routes/user.js
services/badgeService.js
views/includes/navbar.ejs
views/listings/show.ejs
views/users/profile.ejs
views/users/wishlist.ejs

🚀 Major Features Delivered:
🏆 Achievement Badge System - 12 predefined badges with rarity levels and automatic awarding
🎯 Travel Goals & Bucket List - Full CRUD system for setting and tracking travel destinations
❤️ Advanced Wishlist System - Priority levels, notes, privacy controls, and filtering
📊 Enhanced Profile Analytics - Completion tracking, statistics dashboard, activity timeline
🔒 Privacy & Security Controls - Granular privacy settings for profile visibility
📱 Modern Responsive UI - Tabbed interface, cards, animations, mobile-optimized
🛠️ Technical Architecture:
https://github.com/user-attachments/assets/41fbf697-7e4f-4c37-b886-2e1327676d00
Enhanced User Model with comprehensive profile fields
New Models: [Wishlist](vscode-file://vscode-app/c:/Users/121pi/AppData/Local/Programs/Mi …

Implement Enhanced User Profile System with Advanced Features [GSSoC 2025]

---

MODERN_DESIGN_ENHANCEMENTS.md
PR_SUMMARY.md
design-preview.html
public/CSS/style.css
public/JS/script.js
views/about.ejs
views/includes/navbar.ejs

🎨 Complete Design System Overhaul
Modern glassmorphism effects with backdrop blur
Enhanced color palette and gradient system
Improved dark theme with better contrast
Centralized animation variables for consistency
💎 Advanced UI Components
3D transform card effects with perspective
Modern button system with ripple animations
Enhanced navbar with scroll-aware behavior
Interactive theme toggle with rotation effects
---
This PR enhances the WanderLust platform with modern UI/UX improvements and comprehensive documentation templates.
- Added six detailed PR description templates for various feature implementations
- Implemented server-side pagination for listings with 12 items per page
- Enhanced data relationships between reviews, listings, and users
- Modernized UI with glassmorphism …

Modern Design Enhancement [GSSoC 2025]

---

controllers/listings.js
controllers/users.js
models/user.js
routes/listing.js
views/listings/show.ejs
views/users/profile.ejs
views/users/wishlist.ejs

Reverts koushik369mondal/WanderLust#198

Revert "added wishlist destinations"

---

ADVANCED_SEARCH_COMPLETE.md
ADVANCED_SEARCH_FILTERING_SYSTEM.md
controllers/listings.js
public/JS/script.js
views/listings/index.ejs

This PR introduces a comprehensive **Advanced Search & Filtering System** to enhance user experience in finding the perfect listings. The implementation includes real-time search, intelligent filtering, and responsive design optimized for both desktop and mobile users.
- Real-time search suggestions with AJAX
- Instant results without page reloads
- Search highlighting for better visibility
- Debounced input for optimal performance
- **Price Range**: Interactive slider (₹0 - ₹50,000)
- **Rating Filter**: 1★ to 5★ star-based filtering
- **Property Features**: WiFi, Pool, Parking, Pet-friendly, etc.
- **Location Search**: City/region-based filtering
- **Clear All**: One-click filter reset
- Mobile-first approach with Bootstrap 5
- Offcanvas filter panel for mobile devices
- Touch-friendly …

✨ feat: Advanced Search & Filtering System - GSSoC 2025 Contribution

---

.github/dependabot.yml
app.js
controllers/listings.js
controllers/users.js
routes/chatbot.js
routes/user.js
views/includes/chatbot.ejs
views/includes/navbar.ejs
views/layouts/boilerplate.ejs
views/listings/show.ejs
views/recommendations.ejs

closes #201 
@koushik369mondal please check it 
---
This PR implements a Smart Travel Recommendations system and interactive Travel Guide Chatbot.
- Added AI-powered recommendation engine in controllers/listings.js and controllers/users.js
- Created chatbot interface with knowledge base in routes/chatbot.js and views/includes/chatbot.ejs
- Integrated recommendations UI in views/listings/show.ejs and views/recommendations.ejs
- Added new routes for recommendations and chatbot functionality
- Configured Dependabot for automated dependency management

added  ai recommendation

---

.github/dependabot.yml
app.js
controllers/listings.js
controllers/users.js
routes/chatbot.js
routes/user.js
views/includes/chatbot.ejs
views/includes/navbar.ejs
views/layouts/boilerplate.ejs
views/listings/show.ejs
views/recommendations.ejs

closes #69 
@koushik369mondal please check it..
---
This PR implements a comprehensive travel assistance system with chatbot functionality, personalized recommendations, and similar listing suggestions.
- Added travel chatbot with UI component and knowledge base for destinations, activities, and accommodations
- Implemented AI-powered recommendation system that analyzes user preferences from reviews
- Enhanced listing pages with 'You may also like' suggestions based on user history and listing attributes
- Added Dependabot configuration and improved GitHub workflow error handling
- Integrated express.json() middleware for request parsing

added  ai  chatbot

---

.github/dependabot.yml
app.js
controllers/listings.js
controllers/reviews.js
controllers/users.js
routes/chatbot.js
routes/user.js
views/includes/chatbot.ejs
views/includes/navbar.ejs
views/layouts/boilerplate.ejs
views/listings/show.ejs
views/recommendations.ejs

closes #205 
@koushik369mondal please  check it

added  glassmorphism ui  for  better  visibility

---

controllers/users.js
routes/user.js
views/listings/show.ejs

closes #206 
@koushik369mondal please check it..
---
This PR enhances the wishlist functionality with quick-add capabilities and improved user experience.
- Added GET route for wishlist additions in routes/user.js
- Implemented default values for quick-added wishlist items in controllers/users.js
- Added null checks for user.logActivity to prevent errors
- Added redirect parameter to removeFromWishlist for better navigation flow
- Enhanced listing view (show.ejs) with conditional rendering based on wishlist status

fixed wishlist issue

---

app.js
controllers/listings.js
public/JS/weather.js
routes/weather.js
services/weatherService.js
views/listings/show.ejs

closes #227 
@koushik369mondal please check it

added live weather

---

app.js
docs/TRIP_PLANNER.md
docs/VACATION_SLOTS_FIX.md
models/user.js
routes/tripPlanner.js
services/tripPlannerService.js
views/holiday/calendar.ejs
views/includes/navbar.ejs
views/tripPlanner/myTrips.ejs
views/tripPlanner/planner.ejs
views/users/vacation-slots.ejs

closes #241 
@koushik369mondal please check it 
---
This PR implements a complete Trip Planner feature with budget estimation, trip management, and analytics capabilities.
- Added trip planning routes and endpoints in app.js and routes/tripPlanner.js
- Extended user schema with tripPlans array field in models/user.js
- Created TripPlannerService with mock API integrations for travel data
- Implemented UI components for trip planning and trip management
- Added navigation links in the navbar for feature access
- Provided comprehensive documentation in TRIP_PLANNER.md

added  trip planner

---

controllers/listings.js
routes/listing.js
views/listings/index.ejs

closes #238 
@koushik369mondal please check it

added advance filtering option

---

views/listings/compare.ejs
views/listings/index.ejs

closes #249 
@koushik369mondal please check it
---
This PR enhances the listings UI with a modern design refresh and adds a comprehensive comparison feature.
- Transformed compare.ejs to use layout templates with improved styling (background images, gradients, refined colors)
- Updated UI components with sophisticated styling and hover effects
- Added destination comparison feature to index.ejs allowing selection of up to 3 listings
- Implemented interactive UI elements (checkboxes, floating comparison button) with JavaScript functionality
- Created responsive comparison table with visual indicators for best price and highest rated options

fixed comparison issue

---

README.md
TODO.md
app.js
debugAdmin.js
docs/ADMIN_DASHBOARD.md
fixAdmin.js
models/user.js
public/CSS/admin-dashboard.css
public/JS/admin-dashboard.js
quickAdmin.js
routes/admin.js
test-admin-dashboard.js
testUser.js
views/admin/dashboard.ejs

closes #242 
admin
username:admin
password:@ Admin123
@koushik369mondal please check it
---
This PR implements a comprehensive Admin Analytics Dashboard with full management capabilities for the Wanderlust application.
- Added backend API endpoints for analytics, user/listing/review management, and system settings
- Implemented frontend with Chart.js visualizations, data tables with pagination, and responsive design
- Created utility scripts for admin account management and testing
- Added comprehensive documentation and testing tools
- Enhanced user schema and authentication handling
- Implemented dedicated CSS styling and JavaScript functionality

added  admin-dash
